version: '2'
services:
  procesoname-mysql:
    image: mysql
    #build: .
    environment:
      - MYSQL_ROOT_PASSWORD=rodo123
  django-clase: 
    image: docker-api-devf
    ports:
      - "8000:8000"
