# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20170929_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='shalashala',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
